/**
*
*Copyright 2010 Microsoft Corp
*
*Licensed under the Apache License, Version 2.0 (the "License");
*you may not use this file except in compliance with the License.
*You may obtain a copy of the License at
*
*http://www.apache.org/licenses/LICENSE-2.0
*
*Unless required by applicable law or agreed to in writing, software
*distributed under the License is distributed on an "AS IS" BASIS,
*WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*See the License for the specific language governing permissions and
*limitations under the License.
*/
/**
* This code was generated by the tool 'odatagen'.
* Runtime Version:1.0
*
* Changes to this file may cause incorrect behavior and will be lost if
* the code is regenerated.
*/
/**
* Defines default Data Service URL for this proxy class
*/
#define DEFAULT_SERVICE_URL @""


#define DataServiceVersion @"1.0"

#import "ODataObject.h"
#import "ObjectContext.h"
#import "DataServiceQuery.h"
#import "ODataGUID.h"
#import "ODataBool.h"
#import  "mProperties.h"


/**
 * @interface:Category
 * @Type:EntityType
 
 * @key:CategoryID* 
 */
@interface NorthwindModel_Category : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_CategoryID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_CategoryName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:Max
	* @FixedLength:false
	*/
	NSString *m_Description;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Binary
	*/
	NSData *m_Picture;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Products_Categories
	* @FromRole:Categories
	* @ToRole:Products
	*/
	NSMutableArray *m_Products;
	
}

@property ( nonatomic , retain , getter=getCategoryID , setter=setCategoryID )NSNumber *m_CategoryID;
@property ( nonatomic , retain , getter=getCategoryName , setter=setCategoryName ) NSString *m_CategoryName;
@property ( nonatomic , retain , getter=getDescription , setter=setDescription ) NSString *m_Description;
@property ( nonatomic , retain , getter=getPicture , setter=setPicture )NSData *m_Picture;
@property ( nonatomic , retain , getter=getProducts , setter=setProducts )NSMutableArray *m_Products;

+ (id) CreateCategoryWithcategoryid:(NSNumber *)aCategoryID categoryname:(NSString *)aCategoryName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:CustomerDemographic
 * @Type:EntityType
 
 * @key:CustomerTypeID* 
 */
@interface NorthwindModel_CustomerDemographic : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:10
	* @FixedLength:true
	*/
	NSString *m_CustomerTypeID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:Max
	* @FixedLength:false
	*/
	NSString *m_CustomerDesc;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:CustomerCustomerDemo
	* @FromRole:CustomerDemographics
	* @ToRole:Customers
	*/
	NSMutableArray *m_Customers;
	
}

@property ( nonatomic , retain , getter=getCustomerTypeID , setter=setCustomerTypeID ) NSString *m_CustomerTypeID;
@property ( nonatomic , retain , getter=getCustomerDesc , setter=setCustomerDesc ) NSString *m_CustomerDesc;
@property ( nonatomic , retain , getter=getCustomers , setter=setCustomers )NSMutableArray *m_Customers;

+ (id) CreateCustomerDemographicWithcustomertypeid:(NSString *)aCustomerTypeID;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Customer
 * @Type:EntityType
 
 * @key:CustomerID* 
 */
@interface NorthwindModel_Customer : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:5
	* @FixedLength:true
	*/
	NSString *m_CustomerID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_CompanyName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:30
	* @FixedLength:false
	*/
	NSString *m_ContactName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:30
	* @FixedLength:false
	*/
	NSString *m_ContactTitle;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:60
	* @FixedLength:false
	*/
	NSString *m_Address;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_City;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_Region;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:10
	* @FixedLength:false
	*/
	NSString *m_PostalCode;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_Country;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:24
	* @FixedLength:false
	*/
	NSString *m_Phone;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:24
	* @FixedLength:false
	*/
	NSString *m_Fax;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Orders_Customers
	* @FromRole:Customers
	* @ToRole:Orders
	*/
	NSMutableArray *m_Orders;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:CustomerCustomerDemo
	* @FromRole:Customers
	* @ToRole:CustomerDemographics
	*/
	NSMutableArray *m_CustomerDemographics;
	
}

@property ( nonatomic , retain , getter=getCustomerID , setter=setCustomerID ) NSString *m_CustomerID;
@property ( nonatomic , retain , getter=getCompanyName , setter=setCompanyName ) NSString *m_CompanyName;
@property ( nonatomic , retain , getter=getContactName , setter=setContactName ) NSString *m_ContactName;
@property ( nonatomic , retain , getter=getContactTitle , setter=setContactTitle ) NSString *m_ContactTitle;
@property ( nonatomic , retain , getter=getAddress , setter=setAddress ) NSString *m_Address;
@property ( nonatomic , retain , getter=getCity , setter=setCity ) NSString *m_City;
@property ( nonatomic , retain , getter=getRegion , setter=setRegion ) NSString *m_Region;
@property ( nonatomic , retain , getter=getPostalCode , setter=setPostalCode ) NSString *m_PostalCode;
@property ( nonatomic , retain , getter=getCountry , setter=setCountry ) NSString *m_Country;
@property ( nonatomic , retain , getter=getPhone , setter=setPhone ) NSString *m_Phone;
@property ( nonatomic , retain , getter=getFax , setter=setFax ) NSString *m_Fax;
@property ( nonatomic , retain , getter=getOrders , setter=setOrders )NSMutableArray *m_Orders;
@property ( nonatomic , retain , getter=getCustomerDemographics , setter=setCustomerDemographics )NSMutableArray *m_CustomerDemographics;

+ (id) CreateCustomerWithcustomerid:(NSString *)aCustomerID companyname:(NSString *)aCompanyName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Employee
 * @Type:EntityType
 
 * @key:EmployeeID* 
 */
@interface NorthwindModel_Employee : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_EmployeeID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:20
	* @FixedLength:false
	*/
	NSString *m_LastName;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:10
	* @FixedLength:false
	*/
	NSString *m_FirstName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:30
	* @FixedLength:false
	*/
	NSString *m_Title;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:25
	* @FixedLength:false
	*/
	NSString *m_TitleOfCourtesy;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_BirthDate;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_HireDate;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:60
	* @FixedLength:false
	*/
	NSString *m_Address;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_City;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_Region;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:10
	* @FixedLength:false
	*/
	NSString *m_PostalCode;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_Country;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:24
	* @FixedLength:false
	*/
	NSString *m_HomePhone;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:4
	* @FixedLength:false
	*/
	NSString *m_Extension;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Binary
	*/
	NSData *m_Photo;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:Max
	* @FixedLength:false
	*/
	NSString *m_Notes;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ReportsTo;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:255
	* @FixedLength:false
	*/
	NSString *m_PhotoPath;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Employees_Employees
	* @FromRole:Employees
	* @ToRole:Employees1
	*/
	NSMutableArray *m_Employees1;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Employees_Employees
	* @FromRole:Employees1
	* @ToRole:Employees
	*/
	NSMutableArray *m_Employee1;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Orders_Employees
	* @FromRole:Employees
	* @ToRole:Orders
	*/
	NSMutableArray *m_Orders;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:EmployeeTerritories
	* @FromRole:Employees
	* @ToRole:Territories
	*/
	NSMutableArray *m_Territories;
	
}

@property ( nonatomic , retain , getter=getEmployeeID , setter=setEmployeeID )NSNumber *m_EmployeeID;
@property ( nonatomic , retain , getter=getLastName , setter=setLastName ) NSString *m_LastName;
@property ( nonatomic , retain , getter=getFirstName , setter=setFirstName ) NSString *m_FirstName;
@property ( nonatomic , retain , getter=getTitle , setter=setTitle ) NSString *m_Title;
@property ( nonatomic , retain , getter=getTitleOfCourtesy , setter=setTitleOfCourtesy ) NSString *m_TitleOfCourtesy;
@property ( nonatomic , retain , getter=getBirthDate , setter=setBirthDate )NSDate *m_BirthDate;
@property ( nonatomic , retain , getter=getHireDate , setter=setHireDate )NSDate *m_HireDate;
@property ( nonatomic , retain , getter=getAddress , setter=setAddress ) NSString *m_Address;
@property ( nonatomic , retain , getter=getCity , setter=setCity ) NSString *m_City;
@property ( nonatomic , retain , getter=getRegion , setter=setRegion ) NSString *m_Region;
@property ( nonatomic , retain , getter=getPostalCode , setter=setPostalCode ) NSString *m_PostalCode;
@property ( nonatomic , retain , getter=getCountry , setter=setCountry ) NSString *m_Country;
@property ( nonatomic , retain , getter=getHomePhone , setter=setHomePhone ) NSString *m_HomePhone;
@property ( nonatomic , retain , getter=getExtension , setter=setExtension ) NSString *m_Extension;
@property ( nonatomic , retain , getter=getPhoto , setter=setPhoto )NSData *m_Photo;
@property ( nonatomic , retain , getter=getNotes , setter=setNotes ) NSString *m_Notes;
@property ( nonatomic , retain , getter=getReportsTo , setter=setReportsTo )NSNumber *m_ReportsTo;
@property ( nonatomic , retain , getter=getPhotoPath , setter=setPhotoPath ) NSString *m_PhotoPath;
@property ( nonatomic , retain , getter=getEmployees1 , setter=setEmployees1 )NSMutableArray *m_Employees1;
@property ( nonatomic , retain , getter=getEmployee1 , setter=setEmployee1 )NSMutableArray *m_Employee1;
@property ( nonatomic , retain , getter=getOrders , setter=setOrders )NSMutableArray *m_Orders;
@property ( nonatomic , retain , getter=getTerritories , setter=setTerritories )NSMutableArray *m_Territories;

+ (id) CreateEmployeeWithemployeeid:(NSNumber *)aEmployeeID lastname:(NSString *)aLastName firstname:(NSString *)aFirstName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Order_Detail
 * @Type:EntityType
 
 * @key:OrderID
 * @key:ProductID* 
 */
@interface NorthwindModel_Order_Detail : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_OrderID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ProductID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_UnitPrice;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int16
	*/
	NSNumber *m_Quantity;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Single
	*/
	NSDecimalNumber *m_Discount;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Order_Details_Orders
	* @FromRole:Order_Details
	* @ToRole:Orders
	*/
	NSMutableArray *m_Order;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Order_Details_Products
	* @FromRole:Order_Details
	* @ToRole:Products
	*/
	NSMutableArray *m_Product;
	
}

@property ( nonatomic , retain , getter=getOrderID , setter=setOrderID )NSNumber *m_OrderID;
@property ( nonatomic , retain , getter=getProductID , setter=setProductID )NSNumber *m_ProductID;
@property ( nonatomic , retain , getter=getUnitPrice , setter=setUnitPrice )NSDecimalNumber *m_UnitPrice;
@property ( nonatomic , retain , getter=getQuantity , setter=setQuantity )NSNumber *m_Quantity;
@property ( nonatomic , retain , getter=getDiscount , setter=setDiscount )NSDecimalNumber *m_Discount;
@property ( nonatomic , retain , getter=getOrder , setter=setOrder )NSMutableArray *m_Order;
@property ( nonatomic , retain , getter=getProduct , setter=setProduct )NSMutableArray *m_Product;

+ (id) CreateOrder_DetailWithorderid:(NSNumber *)aOrderID productid:(NSNumber *)aProductID unitprice:(NSDecimalNumber *)aUnitPrice quantity:(NSNumber *)aQuantity discount:(NSDecimalNumber *)aDiscount;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Order
 * @Type:EntityType
 
 * @key:OrderID* 
 */
@interface NorthwindModel_Order : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_OrderID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:5
	* @FixedLength:true
	*/
	NSString *m_CustomerID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_EmployeeID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_OrderDate;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_RequiredDate;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_ShippedDate;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ShipVia;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_Freight;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_ShipName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:60
	* @FixedLength:false
	*/
	NSString *m_ShipAddress;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_ShipCity;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_ShipRegion;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:10
	* @FixedLength:false
	*/
	NSString *m_ShipPostalCode;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_ShipCountry;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Orders_Customers
	* @FromRole:Orders
	* @ToRole:Customers
	*/
	NSMutableArray *m_Customer;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Orders_Employees
	* @FromRole:Orders
	* @ToRole:Employees
	*/
	NSMutableArray *m_Employee;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Order_Details_Orders
	* @FromRole:Orders
	* @ToRole:Order_Details
	*/
	NSMutableArray *m_Order_Details;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Orders_Shippers
	* @FromRole:Orders
	* @ToRole:Shippers
	*/
	NSMutableArray *m_Shipper;
	
}

@property ( nonatomic , retain , getter=getOrderID , setter=setOrderID )NSNumber *m_OrderID;
@property ( nonatomic , retain , getter=getCustomerID , setter=setCustomerID ) NSString *m_CustomerID;
@property ( nonatomic , retain , getter=getEmployeeID , setter=setEmployeeID )NSNumber *m_EmployeeID;
@property ( nonatomic , retain , getter=getOrderDate , setter=setOrderDate )NSDate *m_OrderDate;
@property ( nonatomic , retain , getter=getRequiredDate , setter=setRequiredDate )NSDate *m_RequiredDate;
@property ( nonatomic , retain , getter=getShippedDate , setter=setShippedDate )NSDate *m_ShippedDate;
@property ( nonatomic , retain , getter=getShipVia , setter=setShipVia )NSNumber *m_ShipVia;
@property ( nonatomic , retain , getter=getFreight , setter=setFreight )NSDecimalNumber *m_Freight;
@property ( nonatomic , retain , getter=getShipName , setter=setShipName ) NSString *m_ShipName;
@property ( nonatomic , retain , getter=getShipAddress , setter=setShipAddress ) NSString *m_ShipAddress;
@property ( nonatomic , retain , getter=getShipCity , setter=setShipCity ) NSString *m_ShipCity;
@property ( nonatomic , retain , getter=getShipRegion , setter=setShipRegion ) NSString *m_ShipRegion;
@property ( nonatomic , retain , getter=getShipPostalCode , setter=setShipPostalCode ) NSString *m_ShipPostalCode;
@property ( nonatomic , retain , getter=getShipCountry , setter=setShipCountry ) NSString *m_ShipCountry;
@property ( nonatomic , retain , getter=getCustomer , setter=setCustomer )NSMutableArray *m_Customer;
@property ( nonatomic , retain , getter=getEmployee , setter=setEmployee )NSMutableArray *m_Employee;
@property ( nonatomic , retain , getter=getOrder_Details , setter=setOrder_Details )NSMutableArray *m_Order_Details;
@property ( nonatomic , retain , getter=getShipper , setter=setShipper )NSMutableArray *m_Shipper;

+ (id) CreateOrderWithorderid:(NSNumber *)aOrderID;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Product
 * @Type:EntityType
 
 * @key:ProductID* 
 */
@interface NorthwindModel_Product : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ProductID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_ProductName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_SupplierID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_CategoryID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:20
	* @FixedLength:false
	*/
	NSString *m_QuantityPerUnit;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_UnitPrice;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int16
	*/
	NSNumber *m_UnitsInStock;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int16
	*/
	NSNumber *m_UnitsOnOrder;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int16
	*/
	NSNumber *m_ReorderLevel;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Boolean
	*/
	ODataBool *m_Discontinued;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Products_Categories
	* @FromRole:Products
	* @ToRole:Categories
	*/
	NSMutableArray *m_Category;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Order_Details_Products
	* @FromRole:Products
	* @ToRole:Order_Details
	*/
	NSMutableArray *m_Order_Details;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Products_Suppliers
	* @FromRole:Products
	* @ToRole:Suppliers
	*/
	NSMutableArray *m_Supplier;
	
}

@property ( nonatomic , retain , getter=getProductID , setter=setProductID )NSNumber *m_ProductID;
@property ( nonatomic , retain , getter=getProductName , setter=setProductName ) NSString *m_ProductName;
@property ( nonatomic , retain , getter=getSupplierID , setter=setSupplierID )NSNumber *m_SupplierID;
@property ( nonatomic , retain , getter=getCategoryID , setter=setCategoryID )NSNumber *m_CategoryID;
@property ( nonatomic , retain , getter=getQuantityPerUnit , setter=setQuantityPerUnit ) NSString *m_QuantityPerUnit;
@property ( nonatomic , retain , getter=getUnitPrice , setter=setUnitPrice )NSDecimalNumber *m_UnitPrice;
@property ( nonatomic , retain , getter=getUnitsInStock , setter=setUnitsInStock )NSNumber *m_UnitsInStock;
@property ( nonatomic , retain , getter=getUnitsOnOrder , setter=setUnitsOnOrder )NSNumber *m_UnitsOnOrder;
@property ( nonatomic , retain , getter=getReorderLevel , setter=setReorderLevel )NSNumber *m_ReorderLevel;
@property ( nonatomic , retain , getter=getDiscontinued , setter=setDiscontinued )ODataBool *m_Discontinued;
@property ( nonatomic , retain , getter=getCategory , setter=setCategory )NSMutableArray *m_Category;
@property ( nonatomic , retain , getter=getOrder_Details , setter=setOrder_Details )NSMutableArray *m_Order_Details;
@property ( nonatomic , retain , getter=getSupplier , setter=setSupplier )NSMutableArray *m_Supplier;

+ (id) CreateProductWithproductid:(NSNumber *)aProductID productname:(NSString *)aProductName discontinued:(ODataBool *)aDiscontinued;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Region
 * @Type:EntityType
 
 * @key:RegionID* 
 */
@interface NorthwindModel_Region : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_RegionID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:50
	* @FixedLength:true
	*/
	NSString *m_RegionDescription;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Territories_Region
	* @FromRole:Region
	* @ToRole:Territories
	*/
	NSMutableArray *m_Territories;
	
}

@property ( nonatomic , retain , getter=getRegionID , setter=setRegionID )NSNumber *m_RegionID;
@property ( nonatomic , retain , getter=getRegionDescription , setter=setRegionDescription ) NSString *m_RegionDescription;
@property ( nonatomic , retain , getter=getTerritories , setter=setTerritories )NSMutableArray *m_Territories;

+ (id) CreateRegionWithregionid:(NSNumber *)aRegionID regiondescription:(NSString *)aRegionDescription;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Shipper
 * @Type:EntityType
 
 * @key:ShipperID* 
 */
@interface NorthwindModel_Shipper : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ShipperID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_CompanyName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:24
	* @FixedLength:false
	*/
	NSString *m_Phone;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Orders_Shippers
	* @FromRole:Shippers
	* @ToRole:Orders
	*/
	NSMutableArray *m_Orders;
	
}

@property ( nonatomic , retain , getter=getShipperID , setter=setShipperID )NSNumber *m_ShipperID;
@property ( nonatomic , retain , getter=getCompanyName , setter=setCompanyName ) NSString *m_CompanyName;
@property ( nonatomic , retain , getter=getPhone , setter=setPhone ) NSString *m_Phone;
@property ( nonatomic , retain , getter=getOrders , setter=setOrders )NSMutableArray *m_Orders;

+ (id) CreateShipperWithshipperid:(NSNumber *)aShipperID companyname:(NSString *)aCompanyName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Supplier
 * @Type:EntityType
 
 * @key:SupplierID* 
 */
@interface NorthwindModel_Supplier : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_SupplierID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_CompanyName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:30
	* @FixedLength:false
	*/
	NSString *m_ContactName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:30
	* @FixedLength:false
	*/
	NSString *m_ContactTitle;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:60
	* @FixedLength:false
	*/
	NSString *m_Address;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_City;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_Region;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:10
	* @FixedLength:false
	*/
	NSString *m_PostalCode;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_Country;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:24
	* @FixedLength:false
	*/
	NSString *m_Phone;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:24
	* @FixedLength:false
	*/
	NSString *m_Fax;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:Max
	* @FixedLength:false
	*/
	NSString *m_HomePage;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Products_Suppliers
	* @FromRole:Suppliers
	* @ToRole:Products
	*/
	NSMutableArray *m_Products;
	
}

@property ( nonatomic , retain , getter=getSupplierID , setter=setSupplierID )NSNumber *m_SupplierID;
@property ( nonatomic , retain , getter=getCompanyName , setter=setCompanyName ) NSString *m_CompanyName;
@property ( nonatomic , retain , getter=getContactName , setter=setContactName ) NSString *m_ContactName;
@property ( nonatomic , retain , getter=getContactTitle , setter=setContactTitle ) NSString *m_ContactTitle;
@property ( nonatomic , retain , getter=getAddress , setter=setAddress ) NSString *m_Address;
@property ( nonatomic , retain , getter=getCity , setter=setCity ) NSString *m_City;
@property ( nonatomic , retain , getter=getRegion , setter=setRegion ) NSString *m_Region;
@property ( nonatomic , retain , getter=getPostalCode , setter=setPostalCode ) NSString *m_PostalCode;
@property ( nonatomic , retain , getter=getCountry , setter=setCountry ) NSString *m_Country;
@property ( nonatomic , retain , getter=getPhone , setter=setPhone ) NSString *m_Phone;
@property ( nonatomic , retain , getter=getFax , setter=setFax ) NSString *m_Fax;
@property ( nonatomic , retain , getter=getHomePage , setter=setHomePage ) NSString *m_HomePage;
@property ( nonatomic , retain , getter=getProducts , setter=setProducts )NSMutableArray *m_Products;

+ (id) CreateSupplierWithsupplierid:(NSNumber *)aSupplierID companyname:(NSString *)aCompanyName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Territory
 * @Type:EntityType
 
 * @key:TerritoryID* 
 */
@interface NorthwindModel_Territory : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:20
	* @FixedLength:false
	*/
	NSString *m_TerritoryID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:50
	* @FixedLength:true
	*/
	NSString *m_TerritoryDescription;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_RegionID;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:FK_Territories_Region
	* @FromRole:Territories
	* @ToRole:Region
	*/
	NSMutableArray *m_Region;
	
	/**
	* @Type:NavigationProperty
	* @Relationship:EmployeeTerritories
	* @FromRole:Territories
	* @ToRole:Employees
	*/
	NSMutableArray *m_Employees;
	
}

@property ( nonatomic , retain , getter=getTerritoryID , setter=setTerritoryID ) NSString *m_TerritoryID;
@property ( nonatomic , retain , getter=getTerritoryDescription , setter=setTerritoryDescription ) NSString *m_TerritoryDescription;
@property ( nonatomic , retain , getter=getRegionID , setter=setRegionID )NSNumber *m_RegionID;
@property ( nonatomic , retain , getter=getRegion , setter=setRegion )NSMutableArray *m_Region;
@property ( nonatomic , retain , getter=getEmployees , setter=setEmployees )NSMutableArray *m_Employees;

+ (id) CreateTerritoryWithterritoryid:(NSString *)aTerritoryID territorydescription:(NSString *)aTerritoryDescription regionid:(NSNumber *)aRegionID;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Alphabetical_list_of_product
 * @Type:EntityType
 
 * @key:ProductID
 * @key:ProductName
 * @key:Discontinued
 * @key:CategoryName* 
 */
@interface NorthwindModel_Alphabetical_list_of_product : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ProductID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_ProductName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_SupplierID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_CategoryID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:20
	* @FixedLength:false
	*/
	NSString *m_QuantityPerUnit;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_UnitPrice;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int16
	*/
	NSNumber *m_UnitsInStock;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int16
	*/
	NSNumber *m_UnitsOnOrder;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int16
	*/
	NSNumber *m_ReorderLevel;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Boolean
	*/
	ODataBool *m_Discontinued;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_CategoryName;
	
}

@property ( nonatomic , retain , getter=getProductID , setter=setProductID )NSNumber *m_ProductID;
@property ( nonatomic , retain , getter=getProductName , setter=setProductName ) NSString *m_ProductName;
@property ( nonatomic , retain , getter=getSupplierID , setter=setSupplierID )NSNumber *m_SupplierID;
@property ( nonatomic , retain , getter=getCategoryID , setter=setCategoryID )NSNumber *m_CategoryID;
@property ( nonatomic , retain , getter=getQuantityPerUnit , setter=setQuantityPerUnit ) NSString *m_QuantityPerUnit;
@property ( nonatomic , retain , getter=getUnitPrice , setter=setUnitPrice )NSDecimalNumber *m_UnitPrice;
@property ( nonatomic , retain , getter=getUnitsInStock , setter=setUnitsInStock )NSNumber *m_UnitsInStock;
@property ( nonatomic , retain , getter=getUnitsOnOrder , setter=setUnitsOnOrder )NSNumber *m_UnitsOnOrder;
@property ( nonatomic , retain , getter=getReorderLevel , setter=setReorderLevel )NSNumber *m_ReorderLevel;
@property ( nonatomic , retain , getter=getDiscontinued , setter=setDiscontinued )ODataBool *m_Discontinued;
@property ( nonatomic , retain , getter=getCategoryName , setter=setCategoryName ) NSString *m_CategoryName;

+ (id) CreateAlphabetical_list_of_productWithproductid:(NSNumber *)aProductID productname:(NSString *)aProductName discontinued:(ODataBool *)aDiscontinued categoryname:(NSString *)aCategoryName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Category_Sales_for_1997
 * @Type:EntityType
 
 * @key:CategoryName* 
 */
@interface NorthwindModel_Category_Sales_for_1997 : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_CategoryName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_CategorySales;
	
}

@property ( nonatomic , retain , getter=getCategoryName , setter=setCategoryName ) NSString *m_CategoryName;
@property ( nonatomic , retain , getter=getCategorySales , setter=setCategorySales )NSDecimalNumber *m_CategorySales;

+ (id) CreateCategory_Sales_for_1997Withcategoryname:(NSString *)aCategoryName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Current_Product_List
 * @Type:EntityType
 
 * @key:ProductID
 * @key:ProductName* 
 */
@interface NorthwindModel_Current_Product_List : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ProductID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_ProductName;
	
}

@property ( nonatomic , retain , getter=getProductID , setter=setProductID )NSNumber *m_ProductID;
@property ( nonatomic , retain , getter=getProductName , setter=setProductName ) NSString *m_ProductName;

+ (id) CreateCurrent_Product_ListWithproductid:(NSNumber *)aProductID productname:(NSString *)aProductName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Customer_and_Suppliers_by_City
 * @Type:EntityType
 
 * @key:CompanyName
 * @key:Relationship* 
 */
@interface NorthwindModel_Customer_and_Suppliers_by_City : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_City;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_CompanyName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:30
	* @FixedLength:false
	*/
	NSString *m_ContactName;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:9
	* @FixedLength:false
	*/
	NSString *m_Relationship;
	
}

@property ( nonatomic , retain , getter=getCity , setter=setCity ) NSString *m_City;
@property ( nonatomic , retain , getter=getCompanyName , setter=setCompanyName ) NSString *m_CompanyName;
@property ( nonatomic , retain , getter=getContactName , setter=setContactName ) NSString *m_ContactName;
@property ( nonatomic , retain , getter=getRelationship , setter=setRelationship ) NSString *m_Relationship;

+ (id) CreateCustomer_and_Suppliers_by_CityWithcompanyname:(NSString *)aCompanyName relationship:(NSString *)aRelationship;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Invoice
 * @Type:EntityType
 
 * @key:CustomerName
 * @key:Salesperson
 * @key:OrderID
 * @key:ShipperName
 * @key:ProductID
 * @key:ProductName
 * @key:UnitPrice
 * @key:Quantity
 * @key:Discount* 
 */
@interface NorthwindModel_Invoice : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_ShipName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:60
	* @FixedLength:false
	*/
	NSString *m_ShipAddress;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_ShipCity;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_ShipRegion;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:10
	* @FixedLength:false
	*/
	NSString *m_ShipPostalCode;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_ShipCountry;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:5
	* @FixedLength:true
	*/
	NSString *m_CustomerID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_CustomerName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:60
	* @FixedLength:false
	*/
	NSString *m_Address;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_City;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_Region;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:10
	* @FixedLength:false
	*/
	NSString *m_PostalCode;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_Country;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:31
	* @FixedLength:false
	*/
	NSString *m_Salesperson;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_OrderID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_OrderDate;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_RequiredDate;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_ShippedDate;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_ShipperName;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ProductID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_ProductName;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_UnitPrice;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int16
	*/
	NSNumber *m_Quantity;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Single
	*/
	NSDecimalNumber *m_Discount;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_ExtendedPrice;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_Freight;
	
}

@property ( nonatomic , retain , getter=getShipName , setter=setShipName ) NSString *m_ShipName;
@property ( nonatomic , retain , getter=getShipAddress , setter=setShipAddress ) NSString *m_ShipAddress;
@property ( nonatomic , retain , getter=getShipCity , setter=setShipCity ) NSString *m_ShipCity;
@property ( nonatomic , retain , getter=getShipRegion , setter=setShipRegion ) NSString *m_ShipRegion;
@property ( nonatomic , retain , getter=getShipPostalCode , setter=setShipPostalCode ) NSString *m_ShipPostalCode;
@property ( nonatomic , retain , getter=getShipCountry , setter=setShipCountry ) NSString *m_ShipCountry;
@property ( nonatomic , retain , getter=getCustomerID , setter=setCustomerID ) NSString *m_CustomerID;
@property ( nonatomic , retain , getter=getCustomerName , setter=setCustomerName ) NSString *m_CustomerName;
@property ( nonatomic , retain , getter=getAddress , setter=setAddress ) NSString *m_Address;
@property ( nonatomic , retain , getter=getCity , setter=setCity ) NSString *m_City;
@property ( nonatomic , retain , getter=getRegion , setter=setRegion ) NSString *m_Region;
@property ( nonatomic , retain , getter=getPostalCode , setter=setPostalCode ) NSString *m_PostalCode;
@property ( nonatomic , retain , getter=getCountry , setter=setCountry ) NSString *m_Country;
@property ( nonatomic , retain , getter=getSalesperson , setter=setSalesperson ) NSString *m_Salesperson;
@property ( nonatomic , retain , getter=getOrderID , setter=setOrderID )NSNumber *m_OrderID;
@property ( nonatomic , retain , getter=getOrderDate , setter=setOrderDate )NSDate *m_OrderDate;
@property ( nonatomic , retain , getter=getRequiredDate , setter=setRequiredDate )NSDate *m_RequiredDate;
@property ( nonatomic , retain , getter=getShippedDate , setter=setShippedDate )NSDate *m_ShippedDate;
@property ( nonatomic , retain , getter=getShipperName , setter=setShipperName ) NSString *m_ShipperName;
@property ( nonatomic , retain , getter=getProductID , setter=setProductID )NSNumber *m_ProductID;
@property ( nonatomic , retain , getter=getProductName , setter=setProductName ) NSString *m_ProductName;
@property ( nonatomic , retain , getter=getUnitPrice , setter=setUnitPrice )NSDecimalNumber *m_UnitPrice;
@property ( nonatomic , retain , getter=getQuantity , setter=setQuantity )NSNumber *m_Quantity;
@property ( nonatomic , retain , getter=getDiscount , setter=setDiscount )NSDecimalNumber *m_Discount;
@property ( nonatomic , retain , getter=getExtendedPrice , setter=setExtendedPrice )NSDecimalNumber *m_ExtendedPrice;
@property ( nonatomic , retain , getter=getFreight , setter=setFreight )NSDecimalNumber *m_Freight;

+ (id) CreateInvoiceWithcustomername:(NSString *)aCustomerName salesperson:(NSString *)aSalesperson orderid:(NSNumber *)aOrderID shippername:(NSString *)aShipperName productid:(NSNumber *)aProductID productname:(NSString *)aProductName unitprice:(NSDecimalNumber *)aUnitPrice quantity:(NSNumber *)aQuantity discount:(NSDecimalNumber *)aDiscount;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Order_Details_Extended
 * @Type:EntityType
 
 * @key:OrderID
 * @key:ProductID
 * @key:ProductName
 * @key:UnitPrice
 * @key:Quantity
 * @key:Discount* 
 */
@interface NorthwindModel_Order_Details_Extended : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_OrderID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ProductID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_ProductName;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_UnitPrice;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int16
	*/
	NSNumber *m_Quantity;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Single
	*/
	NSDecimalNumber *m_Discount;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_ExtendedPrice;
	
}

@property ( nonatomic , retain , getter=getOrderID , setter=setOrderID )NSNumber *m_OrderID;
@property ( nonatomic , retain , getter=getProductID , setter=setProductID )NSNumber *m_ProductID;
@property ( nonatomic , retain , getter=getProductName , setter=setProductName ) NSString *m_ProductName;
@property ( nonatomic , retain , getter=getUnitPrice , setter=setUnitPrice )NSDecimalNumber *m_UnitPrice;
@property ( nonatomic , retain , getter=getQuantity , setter=setQuantity )NSNumber *m_Quantity;
@property ( nonatomic , retain , getter=getDiscount , setter=setDiscount )NSDecimalNumber *m_Discount;
@property ( nonatomic , retain , getter=getExtendedPrice , setter=setExtendedPrice )NSDecimalNumber *m_ExtendedPrice;

+ (id) CreateOrder_Details_ExtendedWithorderid:(NSNumber *)aOrderID productid:(NSNumber *)aProductID productname:(NSString *)aProductName unitprice:(NSDecimalNumber *)aUnitPrice quantity:(NSNumber *)aQuantity discount:(NSDecimalNumber *)aDiscount;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Order_Subtotal
 * @Type:EntityType
 
 * @key:OrderID* 
 */
@interface NorthwindModel_Order_Subtotal : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_OrderID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_Subtotal;
	
}

@property ( nonatomic , retain , getter=getOrderID , setter=setOrderID )NSNumber *m_OrderID;
@property ( nonatomic , retain , getter=getSubtotal , setter=setSubtotal )NSDecimalNumber *m_Subtotal;

+ (id) CreateOrder_SubtotalWithorderid:(NSNumber *)aOrderID;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Orders_Qry
 * @Type:EntityType
 
 * @key:OrderID
 * @key:CompanyName* 
 */
@interface NorthwindModel_Orders_Qry : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_OrderID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:5
	* @FixedLength:true
	*/
	NSString *m_CustomerID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_EmployeeID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_OrderDate;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_RequiredDate;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_ShippedDate;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_ShipVia;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_Freight;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_ShipName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:60
	* @FixedLength:false
	*/
	NSString *m_ShipAddress;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_ShipCity;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_ShipRegion;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:10
	* @FixedLength:false
	*/
	NSString *m_ShipPostalCode;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_ShipCountry;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_CompanyName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:60
	* @FixedLength:false
	*/
	NSString *m_Address;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_City;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_Region;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:10
	* @FixedLength:false
	*/
	NSString *m_PostalCode;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_Country;
	
}

@property ( nonatomic , retain , getter=getOrderID , setter=setOrderID )NSNumber *m_OrderID;
@property ( nonatomic , retain , getter=getCustomerID , setter=setCustomerID ) NSString *m_CustomerID;
@property ( nonatomic , retain , getter=getEmployeeID , setter=setEmployeeID )NSNumber *m_EmployeeID;
@property ( nonatomic , retain , getter=getOrderDate , setter=setOrderDate )NSDate *m_OrderDate;
@property ( nonatomic , retain , getter=getRequiredDate , setter=setRequiredDate )NSDate *m_RequiredDate;
@property ( nonatomic , retain , getter=getShippedDate , setter=setShippedDate )NSDate *m_ShippedDate;
@property ( nonatomic , retain , getter=getShipVia , setter=setShipVia )NSNumber *m_ShipVia;
@property ( nonatomic , retain , getter=getFreight , setter=setFreight )NSDecimalNumber *m_Freight;
@property ( nonatomic , retain , getter=getShipName , setter=setShipName ) NSString *m_ShipName;
@property ( nonatomic , retain , getter=getShipAddress , setter=setShipAddress ) NSString *m_ShipAddress;
@property ( nonatomic , retain , getter=getShipCity , setter=setShipCity ) NSString *m_ShipCity;
@property ( nonatomic , retain , getter=getShipRegion , setter=setShipRegion ) NSString *m_ShipRegion;
@property ( nonatomic , retain , getter=getShipPostalCode , setter=setShipPostalCode ) NSString *m_ShipPostalCode;
@property ( nonatomic , retain , getter=getShipCountry , setter=setShipCountry ) NSString *m_ShipCountry;
@property ( nonatomic , retain , getter=getCompanyName , setter=setCompanyName ) NSString *m_CompanyName;
@property ( nonatomic , retain , getter=getAddress , setter=setAddress ) NSString *m_Address;
@property ( nonatomic , retain , getter=getCity , setter=setCity ) NSString *m_City;
@property ( nonatomic , retain , getter=getRegion , setter=setRegion ) NSString *m_Region;
@property ( nonatomic , retain , getter=getPostalCode , setter=setPostalCode ) NSString *m_PostalCode;
@property ( nonatomic , retain , getter=getCountry , setter=setCountry ) NSString *m_Country;

+ (id) CreateOrders_QryWithorderid:(NSNumber *)aOrderID companyname:(NSString *)aCompanyName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Product_Sales_for_1997
 * @Type:EntityType
 
 * @key:CategoryName
 * @key:ProductName* 
 */
@interface NorthwindModel_Product_Sales_for_1997 : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_CategoryName;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_ProductName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_ProductSales;
	
}

@property ( nonatomic , retain , getter=getCategoryName , setter=setCategoryName ) NSString *m_CategoryName;
@property ( nonatomic , retain , getter=getProductName , setter=setProductName ) NSString *m_ProductName;
@property ( nonatomic , retain , getter=getProductSales , setter=setProductSales )NSDecimalNumber *m_ProductSales;

+ (id) CreateProduct_Sales_for_1997Withcategoryname:(NSString *)aCategoryName productname:(NSString *)aProductName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Products_Above_Average_Price
 * @Type:EntityType
 
 * @key:ProductName* 
 */
@interface NorthwindModel_Products_Above_Average_Price : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_ProductName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_UnitPrice;
	
}

@property ( nonatomic , retain , getter=getProductName , setter=setProductName ) NSString *m_ProductName;
@property ( nonatomic , retain , getter=getUnitPrice , setter=setUnitPrice )NSDecimalNumber *m_UnitPrice;

+ (id) CreateProducts_Above_Average_PriceWithproductname:(NSString *)aProductName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Products_by_Category
 * @Type:EntityType
 
 * @key:CategoryName
 * @key:ProductName
 * @key:Discontinued* 
 */
@interface NorthwindModel_Products_by_Category : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_CategoryName;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_ProductName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.String
	* @MaxLength:20
	* @FixedLength:false
	*/
	NSString *m_QuantityPerUnit;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Int16
	*/
	NSNumber *m_UnitsInStock;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Boolean
	*/
	ODataBool *m_Discontinued;
	
}

@property ( nonatomic , retain , getter=getCategoryName , setter=setCategoryName ) NSString *m_CategoryName;
@property ( nonatomic , retain , getter=getProductName , setter=setProductName ) NSString *m_ProductName;
@property ( nonatomic , retain , getter=getQuantityPerUnit , setter=setQuantityPerUnit ) NSString *m_QuantityPerUnit;
@property ( nonatomic , retain , getter=getUnitsInStock , setter=setUnitsInStock )NSNumber *m_UnitsInStock;
@property ( nonatomic , retain , getter=getDiscontinued , setter=setDiscontinued )ODataBool *m_Discontinued;

+ (id) CreateProducts_by_CategoryWithcategoryname:(NSString *)aCategoryName productname:(NSString *)aProductName discontinued:(ODataBool *)aDiscontinued;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Sales_by_Category
 * @Type:EntityType
 
 * @key:CategoryID
 * @key:CategoryName
 * @key:ProductName* 
 */
@interface NorthwindModel_Sales_by_Category : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_CategoryID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:15
	* @FixedLength:false
	*/
	NSString *m_CategoryName;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_ProductName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_ProductSales;
	
}

@property ( nonatomic , retain , getter=getCategoryID , setter=setCategoryID )NSNumber *m_CategoryID;
@property ( nonatomic , retain , getter=getCategoryName , setter=setCategoryName ) NSString *m_CategoryName;
@property ( nonatomic , retain , getter=getProductName , setter=setProductName ) NSString *m_ProductName;
@property ( nonatomic , retain , getter=getProductSales , setter=setProductSales )NSDecimalNumber *m_ProductSales;

+ (id) CreateSales_by_CategoryWithcategoryid:(NSNumber *)aCategoryID categoryname:(NSString *)aCategoryName productname:(NSString *)aProductName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Sales_Totals_by_Amount
 * @Type:EntityType
 
 * @key:OrderID
 * @key:CompanyName* 
 */
@interface NorthwindModel_Sales_Totals_by_Amount : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_SaleAmount;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_OrderID;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.String
	* @MaxLength:40
	* @FixedLength:false
	*/
	NSString *m_CompanyName;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_ShippedDate;
	
}

@property ( nonatomic , retain , getter=getSaleAmount , setter=setSaleAmount )NSDecimalNumber *m_SaleAmount;
@property ( nonatomic , retain , getter=getOrderID , setter=setOrderID )NSNumber *m_OrderID;
@property ( nonatomic , retain , getter=getCompanyName , setter=setCompanyName ) NSString *m_CompanyName;
@property ( nonatomic , retain , getter=getShippedDate , setter=setShippedDate )NSDate *m_ShippedDate;

+ (id) CreateSales_Totals_by_AmountWithorderid:(NSNumber *)aOrderID companyname:(NSString *)aCompanyName;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Summary_of_Sales_by_Quarter
 * @Type:EntityType
 
 * @key:OrderID* 
 */
@interface NorthwindModel_Summary_of_Sales_by_Quarter : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_ShippedDate;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_OrderID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_Subtotal;
	
}

@property ( nonatomic , retain , getter=getShippedDate , setter=setShippedDate )NSDate *m_ShippedDate;
@property ( nonatomic , retain , getter=getOrderID , setter=setOrderID )NSNumber *m_OrderID;
@property ( nonatomic , retain , getter=getSubtotal , setter=setSubtotal )NSDecimalNumber *m_Subtotal;

+ (id) CreateSummary_of_Sales_by_QuarterWithorderid:(NSNumber *)aOrderID;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * @interface:Summary_of_Sales_by_Year
 * @Type:EntityType
 
 * @key:OrderID* 
 */
@interface NorthwindModel_Summary_of_Sales_by_Year : ODataObject
{
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.DateTime
	*/
	NSDate *m_ShippedDate;
	
	/**
	* @Type:EntityProperty
	* NotNullable
	* @EdmType:Edm.Int32
	*/
	NSNumber *m_OrderID;
	
	/**
	* @Type:EntityProperty
	* @EdmType:Edm.Decimal
	*/
	NSDecimalNumber *m_Subtotal;
	
}

@property ( nonatomic , retain , getter=getShippedDate , setter=setShippedDate )NSDate *m_ShippedDate;
@property ( nonatomic , retain , getter=getOrderID , setter=setOrderID )NSNumber *m_OrderID;
@property ( nonatomic , retain , getter=getSubtotal , setter=setSubtotal )NSDecimalNumber *m_Subtotal;

+ (id) CreateSummary_of_Sales_by_YearWithorderid:(NSNumber *)aOrderID;
- (id) init;
- (id) initWithUri:(NSString*)anUri;
@end

/**
 * Container interface NorthwindEntities, Namespace: NorthwindModel
 */
@interface NorthwindEntities : ObjectContext
{
	 NSString *m_OData_etag;
	 DataServiceQuery *m_Categories;
	 DataServiceQuery *m_CustomerDemographics;
	 DataServiceQuery *m_Customers;
	 DataServiceQuery *m_Employees;
	 DataServiceQuery *m_Order_Details;
	 DataServiceQuery *m_Orders;
	 DataServiceQuery *m_Products;
	 DataServiceQuery *m_Regions;
	 DataServiceQuery *m_Shippers;
	 DataServiceQuery *m_Suppliers;
	 DataServiceQuery *m_Territories;
	 DataServiceQuery *m_Alphabetical_list_of_products;
	 DataServiceQuery *m_Category_Sales_for_1997;
	 DataServiceQuery *m_Current_Product_Lists;
	 DataServiceQuery *m_Customer_and_Suppliers_by_Cities;
	 DataServiceQuery *m_Invoices;
	 DataServiceQuery *m_Order_Details_Extendeds;
	 DataServiceQuery *m_Order_Subtotals;
	 DataServiceQuery *m_Orders_Qries;
	 DataServiceQuery *m_Product_Sales_for_1997;
	 DataServiceQuery *m_Products_Above_Average_Prices;
	 DataServiceQuery *m_Products_by_Categories;
	 DataServiceQuery *m_Sales_by_Categories;
	 DataServiceQuery *m_Sales_Totals_by_Amounts;
	 DataServiceQuery *m_Summary_of_Sales_by_Quarters;
	 DataServiceQuery *m_Summary_of_Sales_by_Years;
	
}

@property ( nonatomic , retain , getter=getEtag , setter=setEtag )NSString *m_OData_etag;
@property ( nonatomic , retain , getter=getCategories , setter=setCategories ) DataServiceQuery *m_Categories;
@property ( nonatomic , retain , getter=getCustomerDemographics , setter=setCustomerDemographics ) DataServiceQuery *m_CustomerDemographics;
@property ( nonatomic , retain , getter=getCustomers , setter=setCustomers ) DataServiceQuery *m_Customers;
@property ( nonatomic , retain , getter=getEmployees , setter=setEmployees ) DataServiceQuery *m_Employees;
@property ( nonatomic , retain , getter=getOrder_Details , setter=setOrder_Details ) DataServiceQuery *m_Order_Details;
@property ( nonatomic , retain , getter=getOrders , setter=setOrders ) DataServiceQuery *m_Orders;
@property ( nonatomic , retain , getter=getProducts , setter=setProducts ) DataServiceQuery *m_Products;
@property ( nonatomic , retain , getter=getRegions , setter=setRegions ) DataServiceQuery *m_Regions;
@property ( nonatomic , retain , getter=getShippers , setter=setShippers ) DataServiceQuery *m_Shippers;
@property ( nonatomic , retain , getter=getSuppliers , setter=setSuppliers ) DataServiceQuery *m_Suppliers;
@property ( nonatomic , retain , getter=getTerritories , setter=setTerritories ) DataServiceQuery *m_Territories;
@property ( nonatomic , retain , getter=getAlphabetical_list_of_products , setter=setAlphabetical_list_of_products ) DataServiceQuery *m_Alphabetical_list_of_products;
@property ( nonatomic , retain , getter=getCategory_Sales_for_1997 , setter=setCategory_Sales_for_1997 ) DataServiceQuery *m_Category_Sales_for_1997;
@property ( nonatomic , retain , getter=getCurrent_Product_Lists , setter=setCurrent_Product_Lists ) DataServiceQuery *m_Current_Product_Lists;
@property ( nonatomic , retain , getter=getCustomer_and_Suppliers_by_Cities , setter=setCustomer_and_Suppliers_by_Cities ) DataServiceQuery *m_Customer_and_Suppliers_by_Cities;
@property ( nonatomic , retain , getter=getInvoices , setter=setInvoices ) DataServiceQuery *m_Invoices;
@property ( nonatomic , retain , getter=getOrder_Details_Extendeds , setter=setOrder_Details_Extendeds ) DataServiceQuery *m_Order_Details_Extendeds;
@property ( nonatomic , retain , getter=getOrder_Subtotals , setter=setOrder_Subtotals ) DataServiceQuery *m_Order_Subtotals;
@property ( nonatomic , retain , getter=getOrders_Qries , setter=setOrders_Qries ) DataServiceQuery *m_Orders_Qries;
@property ( nonatomic , retain , getter=getProduct_Sales_for_1997 , setter=setProduct_Sales_for_1997 ) DataServiceQuery *m_Product_Sales_for_1997;
@property ( nonatomic , retain , getter=getProducts_Above_Average_Prices , setter=setProducts_Above_Average_Prices ) DataServiceQuery *m_Products_Above_Average_Prices;
@property ( nonatomic , retain , getter=getProducts_by_Categories , setter=setProducts_by_Categories ) DataServiceQuery *m_Products_by_Categories;
@property ( nonatomic , retain , getter=getSales_by_Categories , setter=setSales_by_Categories ) DataServiceQuery *m_Sales_by_Categories;
@property ( nonatomic , retain , getter=getSales_Totals_by_Amounts , setter=setSales_Totals_by_Amounts ) DataServiceQuery *m_Sales_Totals_by_Amounts;
@property ( nonatomic , retain , getter=getSummary_of_Sales_by_Quarters , setter=setSummary_of_Sales_by_Quarters ) DataServiceQuery *m_Summary_of_Sales_by_Quarters;
@property ( nonatomic , retain , getter=getSummary_of_Sales_by_Years , setter=setSummary_of_Sales_by_Years ) DataServiceQuery *m_Summary_of_Sales_by_Years;

- (id) init;
- (id) initWithUri:(NSString*)anUri credential:(id)acredential;
- (id) categories;
- (id) customerdemographics;
- (id) customers;
- (id) employees;
- (id) order_details;
- (id) orders;
- (id) products;
- (id) regions;
- (id) shippers;
- (id) suppliers;
- (id) territories;
- (id) alphabetical_list_of_products;
- (id) category_sales_for_1997;
- (id) current_product_lists;
- (id) customer_and_suppliers_by_cities;
- (id) invoices;
- (id) order_details_extendeds;
- (id) order_subtotals;
- (id) orders_qries;
- (id) product_sales_for_1997;
- (id) products_above_average_prices;
- (id) products_by_categories;
- (id) sales_by_categories;
- (id) sales_totals_by_amounts;
- (id) summary_of_sales_by_quarters;
- (id) summary_of_sales_by_years;
- (void) addToCategories:(id)anObject;
- (void) addToCustomerDemographics:(id)anObject;
- (void) addToCustomers:(id)anObject;
- (void) addToEmployees:(id)anObject;
- (void) addToOrder_Details:(id)anObject;
- (void) addToOrders:(id)anObject;
- (void) addToProducts:(id)anObject;
- (void) addToRegions:(id)anObject;
- (void) addToShippers:(id)anObject;
- (void) addToSuppliers:(id)anObject;
- (void) addToTerritories:(id)anObject;
- (void) addToAlphabetical_list_of_products:(id)anObject;
- (void) addToCategory_Sales_for_1997:(id)anObject;
- (void) addToCurrent_Product_Lists:(id)anObject;
- (void) addToCustomer_and_Suppliers_by_Cities:(id)anObject;
- (void) addToInvoices:(id)anObject;
- (void) addToOrder_Details_Extendeds:(id)anObject;
- (void) addToOrder_Subtotals:(id)anObject;
- (void) addToOrders_Qries:(id)anObject;
- (void) addToProduct_Sales_for_1997:(id)anObject;
- (void) addToProducts_Above_Average_Prices:(id)anObject;
- (void) addToProducts_by_Categories:(id)anObject;
- (void) addToSales_by_Categories:(id)anObject;
- (void) addToSales_Totals_by_Amounts:(id)anObject;
- (void) addToSummary_of_Sales_by_Quarters:(id)anObject;
- (void) addToSummary_of_Sales_by_Years:(id)anObject;

@end
